version: '3'
services:
  frontend:
    build: front/
    container_name: frontend
    ports:
      - 3000:3000
      - 5430:5430
    networks:
      - APInetwork
    depends_on:
      - backend
      - database
    volumes:
      - /Users/aboulhaj/Desktop/Projects/ft_transcendence/front/src:/frontend/src:rw
      - /Users/aboulhaj/Desktop/Projects/ft_transcendence/front/public:/frontend/public:rw
      # - /Users/aboulhaj/Desktop/Projects/ft_transcendence/G_Class:/G_Class:rw
  backend:
    build: backend/
    container_name: backend
    env_file:
      - backend/.env
    ports:
      - 80:80
    networks:
      - APInetwork
    depends_on:
      - database
    volumes:
      # - /Users/aboulhaj/Desktop/Projects/ft_transcendence/G_Class:/app/G_Class:rw
      - /Users/aboulhaj/Desktop/Projects/ft_transcendence/backend/src:/app/src:rw
      - /Users/aboulhaj/Desktop/Projects/ft_transcendence/backend/prisma:/app/prisma:rw
  database:
    image: postgres:13
    container_name: database
    env_file:
      - backend/.env
    environment:
      - POSTGRES_PASSWORD=aboulhaj_012345
      - POSTGRES_USER=aboulhaj
      - POSTGRES_DB=transcendance
      - POSTGRES_PORT=5432
    networks:
      - APInetwork
    volumes:
      - /Users/aboulhaj/Desktop/Projects/ft_transcendence/databases/data:/var/lib/postgresql/data
  
networks:
  APInetwork:
    driver: bridge

