version: '3'
services:
  # frontend:
  #   build: front/
  #   container_name: frontend
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - APInetwork
  #   depends_on:
  #     - backend
  #   volumes:
  #     - /Users/mohamed/Documents/Projects/ft_transcendence/front/src:/frontend/src:rw
  #   restart: always
  # backend:
  #   build: backend/
  #   container_name: backend
  #   env_file:
  #     - backend/.env
  #   ports:
  #     - 80:80
  #   networks:
  #     - APInetwork
  #   depends_on:
  #     - database
  #   restart: always
  #   volumes:
  #     - /Users/mohamed/Documents/Projects/ft_transcendence/backend/src:/app/src:rw
  database:
    image: postgres:13
    container_name: database
    env_file:
      - backend/.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    networks:
      - APInetwork
    restart: always
    ports:
      - 5432:5432
    # volumes:
      # - /Users/mohamed/Documents/Projects/ft_transcendence/databases/data:/var/lib/postgresql/data
  
networks:
  APInetwork:
    driver: bridge

