version: "3"
services:
  frontend:
    build: front/
    container_name: frontend
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - APInetwork
    depends_on:
      - backend
  backend:
    build: backend/
    container_name: backend
    env_file:
      - .env
    ports:
      - 80:80
      - 5555:5555
    networks:
      - APInetwork
networks:
  APInetwork:
    driver: bridge
