version: '3'
services:
  # backend:
  #   build: backend/
  #   container_name: backend
  #   env_file:
  #     - backend/.env
  #   ports:
  #     - 6000:6000
  #   networks:
  #     - APInetwork
  #   volumes:
  #     - /Users/mmasstou/Desktop/Projects/ft_transcendence/backend/src:/app/src:rw
  database:
    image: postgres:13
    container_name: database
    env_file:
      - backend/.env
    environment:
      POSTGRES_PASSWORD: "mmasstou_012345"
      POSTGRES_USER: "mmasstou"
      POSTGRES_DB: "db_chat"
      POSTGRES_HOST: "localhost"
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
    networks:
      - APInetwork
    volumes:
      - /Users/mmasstou/Desktop/Projects/ft_transcendence/databases/data:/var/lib/postgresql/data:ro
  

networks:
  APInetwork:
    driver: bridge
